### ISSUE TITLE
Support short form and unified format in one integration

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lendingtree#15]
Select the correct integration to use based on the format of the submitted lead data. This is high priority.

**Comment by cgrayson** [comment]
I'll take a shot at this. I guess the `request.variables` will have to be a union of those from shortform and unfied.

**Comment by alexkwolfe** [comment]
Crap. I didn't think of that, obviously. I wonder how much that will affect the list of variables.

**Comment by cgrayson** [comment]
`shortform` has 42, `unified` has 46, the union of both has 62. (So 16 more than just `unified`, and 20 more than just `shortform`.) 

Since these integrations should do most, if not all, of the mapping work in the integration code, I think it's okay. That is, it will be rare that any integration users will be exposed to this long list of variables. The one customer I looked at currently doesn't have _any_ manual mappings in place for shortform.

**Comment by alexkwolfe** [comment]
But adding LendingTree to their flow will cause the union of Shortform and Unified fields to get added to their flow.

**Comment by cgrayson** [comment]
Oh yeah. Rats. :disappointed: Maybe having the extra old/shortform fields is temporary, until all users are transitioned off of shortform, and at that time those unneeded variables can be removed…? Otherwise this change is a no-go.

**Comment by kcaponeAP** [comment]
I've asked LT if there is a timeframe in existence of when they will stop sending leads using the older / shortform format.
